# Project information
site_name: Cybersecurity 
use_directory_urls: true

# Configuration
theme:
  name: material
  custom_dir: overrides
  favicon: assets/security.svg
  icon:
    # logo: material/rocket-launch
    logo: material/security
    # repo: fontawesome/brands/github
  palette:
    - scheme: slate      # 深色模式
      primary: black
      accent: orange
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono

  toc:
    on_page: true
    depth: 5


# Page tree
nav:

  - CTF:
    - ctf/index.md
    - ctf/event.md
    - Training:
      - ctf/training/index.md
    - Tools:
      - ctf/tools/index.md
    - Writeup:
      - ctf/writeup/index.md
      
  - Offensive-Security:
    - offensive/index.md
    - Preparation:
      - TTPs:
        - offensive/preparation/ttps/index.md
        - offensive/preparation/ttps/apt.md
        - offensive/preparation/ttps/cyber-kill-chain.md
        - offensive/preparation/ttps/att-ck.md
      - Operations:
        - offensive/preparation/operations/index.md
        - offensive/preparation/operations/red-teaming.md
        - offensive/preparation/operations/pentesting.md
      - Training:
        - offensive/preparation/training/index.md
    - Reconnaissance:
      - offensive/reconnaissance/index.md
    - Exploitation:
      - offensive/exploit/index.md
      - Binary-Exploitation:
        - offensive/exploit/binary-exploitation/index.md
    - Credential-Attacks:
      - offensive/credential-attacks/index.md
    - Social-Engineering:
      - offensive/social-engineering/index.md
    - Post-Exploitation:
      - offensive/post-exploitation/index.md
      - Framework:
        - offensive/post-exploitation/frameworks/index.md
      - C2:
        - offensive/post-exploitation/c2/index.md
      - Payloads:
        - offensive/post-exploitation/payloads/index.md
    - Lateral-Movement:
      - offensive/lateral-movement/index.md
    - Red-Team Infrastructure:
      - offensive/redteam-infra/index.md

  - Defensive-Security:
    - defensive/index.md
    - Preparation:
      - IOCs:
        - defensive/preparation/iocs/index.md
      - Operations:
        - Blue-Teaming:
          - defensive/preparation/operations/blue-teaming/index.md
        - SOC:
          - defensive/preparation/operations/soc/index.md
      - Training:
        - defensive/preparation/training/index.md
    - SOC-Analyst:
      - defensive/soc-analyst/index.md
    - Threat-Intelligence:
      - defensive/threat-intelligence/index.md
    - Digital-Forensics:
      - defensive/operations/digital-forensics/index.md
    - Incident-Response:
      - defensive/operations/incident-response/index.md
      - defensive/operations/incident-response/digital-forensics.md
    - DFIR:
      - defensive/dfir/index.md
    - Threat-Hunting:
      - defensive/operations/threat-hunting/index.md
    - Malware-Analysis:
      - defensive/operations/malware-analysis/index.md
    - Defense-System:
      - defensive/operations/defense-system/index.md
      - Zero-Trust:
        - defensive/operations/defense-system/zero-trust/index.md

  - Cryptography: 
    - topics/crypto/index.md
    - topics/crypto/encoding.md
    - topics/crypto/confusion.md
    - topics/crypto/tools.md
    - topics/crypto/attack.md

  - Web:
    - topics/websec/index.md
    - Preparation:
      - topics/websec/preparation/index.md
    - Server-Side:
      - topics/websec/server-side/index.md
    - Web-Browser:
      - topics/websec/web-client/index.md
    - Protocols:
      - topics/websec/protocols/index.md
    - Database:
      - topics/websec/database/index.md
    - Reproduction:
      - topics/websec/reproduction/index.md
    - Protection:
      - topics/websec/protection/waf.md
      - topics/websec/protection/rasp.md 

  - Network:
    - topics/netsec/index.md
    - Traffic-Analysis:
      - topics/netsec/traffic/index.md
      - Packet-Capture:
        - topics/netsec/traffic/packet-capture/index.md
    - Protocol-Security:
      - topics/netsec/protocol-security/index.md
      - E2EE:
        - topics/netsec/protocol-security/e2ee/index.md
    - Network-Attack:
      - topics/netsec/attack/index.md
      - MitM:
        - topics/netsec/attack/mitm/index.md
      - NAT-Traversal:
        - topics/netsec/attack/nat-traversal/index.md
      - Pentesting:
        - topics/netsec/attack/pentesting/index.md
    - Protection:
      - topics/netsec/protection/index.md
      - topics/netsec/protection/firewall.md
    - Wireless-Security:
      - topics/netsec/wireless-security/index.md

  - Cloud:
    - topics/cloudsec/index.md


  - Reverse-Engineering:
    - topics/reverse/index.md
    - Basic-Tools:
      - topics/reverse/basic-tools/hex-editor.md
    - Binary:
      - topics/reverse/binary/index.md
      # - topics/reverse/binary-analysis/static-analysis.md
      # - topics/reverse/binary-analysis/dynamic-analysis.md
      # - topics/reverse/binary-analysis/hybrid-analysis.md
      - Tools:
        - topics/reverse/binary/tools/disassembler.md
        - topics/reverse/binary/tools/debugger.md
        - topics/reverse/binary/tools/symbolic-execution.md
        - topics/reverse/binary/tools/emulator.md
        - topics/reverse/binary/tools/packers.md
        - topics/reverse/binary/tools/unpackers.md
      - Windows/PE:
        - topics/reverse/binary/pe/index.md
        - topics/reverse/binary/pe/debugger.md
      - Linux/ELF:
        - topics/reverse/binary/elf/index.md
      - macOS/Mach-O:
        - topics/reverse/binary/mach-o/index.md
    - File-Formats:
      - topics/reverse/file-formats/index.md
      # - topics/reverse/file-formats/pdf.md
      # - topics/reverse/file-formats/image-formats.md
      # - topics/reverse/file-formats/audio-video.md
    - Protocol:
      - topics/reverse/protocol/index.md
    - Kernel:
      - topics/reverse/kernel/index.md
    - Bytecode:
      - topics/reverse/bytecode/index.md
      - topics/reverse/bytecode/jvm.md
      - topics/reverse/bytecode/clr.md
      - topics/reverse/bytecode/pyc.md
    - Firmware:
      - topics/reverse/firmware/index.md
    - Hardware:
      - topics/reverse/hardware/index.md

  - System:
    - topics/syssec/index.md
    - Binary-Exploitation:
      - topics/syssec/bin-exp/index.md
    - Malware-Analysis:
      - topics/syssec/malware-analysis/index.md
    - Windows:
      - topics/syssec/windows/index.md
    - Activity-Directory:
      - topics/syssec/ad/index.md
    - Linux:
      - topics/syssec/linux/index.md
    - macOS:
      - topics/syssec/macos/index.md
    - Mobile:
      - topics/syssec/mobile/index.md
    - Endpoint-Security:
      - topics/syssec/endpoint-security/index.md

  - Mobile:
    - topics/mobsec/index.md

  - IoT:
    - topics/iotsec/index.md

    

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true 

extra:
  files_server: "https://files.cyberspace.bar"
  # files_server: "https://files.cyberspace.bar/cyberspace-explore"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js